module.exports = {
  ROLES: {
    ADMIN: 'ADMIN',
    USER: 'USER',
  },
  VERDICTS: {
    PENDING: 'PENDING',
    ACCEPTED: 'ACCEPTED',
    WRONG_ANSWER: 'WRONG_ANSWER',
    RUNTIME_ERROR: 'RUNTIME_ERROR',
    TIME_LIMIT_EXCEEDED: 'TIME_LIMIT_EXCEEDED',
    MEMORY_LIMIT_EXCEEDED: 'MEMORY_LIMIT_EXCEEDED',
    COMPILATION_ERROR: 'COMPILATION_ERROR',
  },
  DIFFICULTY: {
    EASY: 'EASY',
    MEDIUM: 'MEDIUM',
    HARD: 'HARD',
  },
  TESTCASE_TYPE: {
    STATIC: 'STATIC',
    GENERATED: 'GENERATED',
  },
};
